version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
    depends_on:
        - node
  node:
    build: .
    command: "npm run build"
    working_dir: /usr/src/app
    expose:
      - 3000
    ports:
      - 3000:3000
      