version: '3.7'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    build: .
    command: npm run build
    working_dir: /usr/src/app
    expose:
      - 3000
    ports:
      - 3000:3000