version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - node
  node:
    build: .
    command: "npm run build"
    working_dir: /usr/src/app
    ports:
      - 3000:3000
  